title: たいとる
description: ほげほげ
# show_downloads: false
# theme: jekyll-theme-minimal
# remote_theme: pages-themes/dinky@v0.2.0
# theme: minima
# remote_theme: pages-themes/minimal@v0.2.0
remote_theme: pages-themes/leap-day@v0.2.0
